services:
  database:
    build: ./database
    env_file:
      - ./database/.env
    ports:
      - "5432:5432"

  api:
    build: ./api
    env_file:
      - ./api/.env
    ports:
      - "5000:5000"
    links:
      - database
  
  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    links:
      - api